version: '3'

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.38.0
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  rain-forecast-service:
    build:
      context: ../assemblyTarget
      dockerfile: ../docker/Dockerfile
    ports:
      - '8085:8085'
    environment:
      - RATE_LIMIT_REQUESTS_PER_SECOND
  spark:
    image: docker.io/bitnami/spark:3.3.0
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '7077:7077'
      - '8080:8080'
    volumes:
      - ../assemblyTarget/weather-processing-job-0.1.0.jar:/opt/lib/weather-processing-job-0.1.0.jar
      - ../data:/opt/data
  spark-worker-1:
    image: docker.io/bitnami/spark:3.3.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2000M
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8181:8081'
    volumes:
      - ../assemblyTarget/weather-processing-job-0.1.0.jar:/opt/lib/weather-processing-job-0.1.0.jar
      - ../data:/opt/data
  spark-worker-2:
    image: docker.io/bitnami/spark:3.3.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2000M
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8281:8081'
    volumes:
      - ../assemblyTarget/weather-processing-job-0.1.0.jar:/opt/lib/weather-processing-job-0.1.0.jar
      - ../data:/opt/data
  spark-submit:
    tty: true
    image: docker.io/bitnami/spark:3.3.0
    command: ["sleep", "infinity"]
    ports:
      - '4040:4040'
    volumes:
      - ../assemblyTarget/weather-processing-job-0.1.0.jar:/opt/lib/weather-processing-job-0.1.0.jar
      - ../data:/opt/data